import 'package:kan_kardesi/models/blood/blood_type_model.dart';
import 'package:kan_kardesi/models/location/city_model.dart';
import 'package:kan_kardesi/models/user/user_model.dart';

class GlobalVariables {
  static UserModel? userModel;
  static String? playerID;
  static String publicKey = "cokgizli";

  // Blood types
  static List<BloodTypeModel> bloodTypes = [];

  static List<CityModel> cities = [
    CityModel(id: 1, name: 'Adana'),
    CityModel(id: 2, name: 'Adıyaman'),
    CityModel(id: 3, name: 'Afyonkarahisar'),
    CityModel(id: 4, name: 'Ağrı'),
    CityModel(id: 5, name: 'Amasya'),
    CityModel(id: 6, name: 'Ankara'),
    CityModel(id: 7, name: 'Antalya'),
    CityModel(id: 8, name: 'Artvin'),
    CityModel(id: 9, name: 'Aydın'),
    CityModel(id: 10, name: 'Balıkesir'),
    CityModel(id: 11, name: 'Bilecik'),
    CityModel(id: 12, name: 'Bingöl'),
    CityModel(id: 13, name: 'Bitlis'),
    CityModel(id: 14, name: 'Bolu'),
    CityModel(id: 15, name: 'Burdur'),
    CityModel(id: 16, name: 'Bursa'),
    CityModel(id: 17, name: 'Çanakkale'),
    CityModel(id: 18, name: 'Çankırı'),
    CityModel(id: 19, name: 'Çorum'),
    CityModel(id: 20, name: 'Denizli'),
    CityModel(id: 21, name: 'Diyarbakır'),
    CityModel(id: 22, name: 'Edirne'),
    CityModel(id: 23, name: 'Elazığ'),
    CityModel(id: 24, name: 'Erzincan'),
    CityModel(id: 25, name: 'Erzurum'),
    CityModel(id: 26, name: 'Eskişehir'),
    CityModel(id: 27, name: 'Gaziantep'),
    CityModel(id: 28, name: 'Giresun'),
    CityModel(id: 29, name: 'Gümüşhane'),
    CityModel(id: 30, name: 'Hakkâri'),
    CityModel(id: 31, name: 'Hatay'),
    CityModel(id: 32, name: 'Isparta'),
    CityModel(id: 33, name: 'Mersin'),
    CityModel(id: 34, name: 'İstanbul'),
    CityModel(id: 35, name: 'İzmir'),
    CityModel(id: 36, name: 'Kars'),
    CityModel(id: 37, name: 'Kastamonu'),
    CityModel(id: 38, name: 'Kayseri'),
    CityModel(id: 39, name: 'Kırklareli'),
    CityModel(id: 40, name: 'Kırşehir'),
    CityModel(id: 41, name: 'Kocaeli'),
    CityModel(id: 42, name: 'Konya'),
    CityModel(id: 43, name: 'Kütahya'),
    CityModel(id: 44, name: 'Malatya'),
    CityModel(id: 45, name: 'Manisa'),
    CityModel(id: 46, name: 'Kahramanmaraş'),
    CityModel(id: 47, name: 'Mardin'),
    CityModel(id: 48, name: 'Muğla'),
    CityModel(id: 49, name: 'Muş'),
    CityModel(id: 50, name: 'Nevşehir'),
    CityModel(id: 51, name: 'Niğde'),
    CityModel(id: 52, name: 'Ordu'),
    CityModel(id: 53, name: 'Rize'),
    CityModel(id: 54, name: 'Sakarya'),
    CityModel(id: 55, name: 'Samsun'),
    CityModel(id: 56, name: 'Siirt'),
    CityModel(id: 57, name: 'Sinop'),
    CityModel(id: 58, name: 'Sivas'),
    CityModel(id: 59, name: 'Tekirdağ'),
    CityModel(id: 60, name: 'Tokat'),
    CityModel(id: 61, name: 'Trabzon'),
    CityModel(id: 62, name: 'Tunceli'),
    CityModel(id: 63, name: 'Şanlıurfa'),
    CityModel(id: 64, name: 'Uşak'),
    CityModel(id: 65, name: 'Van'),
    CityModel(id: 66, name: 'Yozgat'),
    CityModel(id: 67, name: 'Zonguldak'),
    CityModel(id: 68, name: 'Aksaray'),
    CityModel(id: 69, name: 'Bayburt'),
    CityModel(id: 70, name: 'Karaman'),
    CityModel(id: 71, name: 'Kırıkkale'),
    CityModel(id: 72, name: 'Batman'),
    CityModel(id: 73, name: 'Şırnak'),
    CityModel(id: 74, name: 'Bartın'),
    CityModel(id: 75, name: 'Ardahan'),
    CityModel(id: 76, name: 'Iğdır'),
    CityModel(id: 77, name: 'Yalova'),
    CityModel(id: 78, name: 'Karabük'),
    CityModel(id: 79, name: 'Kilis'),
    CityModel(id: 80, name: 'Osmaniye'),
    CityModel(id: 81, name: 'Düzce'),
  ];
}
